apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
  namespace: egs7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testingapi
        image: registry.deti:5000/egs7/testapi:v6
        ports:
        - containerPort: 31311
        env:
          - name: URL
            value: "http://stock:30099/v1/books"
        



