version: '3.7'

services:
  stock:
    image: stock_api:latest
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - .:/usr/src/book_stock
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://user123:password123@db/stock"

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=stock
    expose: 
      - 5432

volumes:
  postgres_data:
